-- Community Builds backend.
-- Public callers may read only explicitly granted columns. All mutations are
-- performed by the community-builds Edge Function with the service role.

create table if not exists public.community_builds (
  id uuid primary key default gen_random_uuid(),
  author_name text not null,
  build_name text not null,
  build_code text not null,
  build_version smallint not null default 2,
  archetype_id text not null,
  positions text[] not null default '{}'::text[],
  level smallint not null,
  status text not null default 'published',
  management_token_hash text not null unique,
  created_at timestamptz not null default clock_timestamp(),

  constraint community_builds_author_name_length
    check (char_length(author_name) between 2 and 32),
  constraint community_builds_build_name_length
    check (char_length(build_name) between 2 and 60),
  constraint community_builds_code_length
    check (char_length(build_code) between 1 and 16384),
  constraint community_builds_code_base64url
    check (build_code ~ '^[A-Za-z0-9_-]+$'),
  constraint community_builds_version_v2 check (build_version = 2),
  constraint community_builds_level_range check (level between 1 and 100),
  constraint community_builds_status
    check (status in ('published', 'hidden')),
  constraint community_builds_token_hash
    check (management_token_hash ~ '^[0-9a-f]{64}$'),
  constraint community_builds_archetype
    check (archetype_id in (
      'gk_shot_stopper', 'gk_sweeper_keeper',
      'def_progressor', 'def_boss', 'def_engine', 'def_marauder',
      'mid_recycler', 'mid_maestro', 'mid_creator', 'mid_spark',
      'fwd_magician', 'fwd_finisher', 'fwd_target'
    )),
  constraint community_builds_positions
    check (
      cardinality(positions) <= 11
      and positions <@ array[
        'GK', 'ST', 'RW', 'LW', 'CAM', 'RM', 'LM',
        'CM', 'CDM', 'RB', 'LB', 'CB'
      ]::text[]
    )
);

comment on table public.community_builds is
  'User-submitted FC Clubs builds. management_token_hash is never publicly selectable.';
comment on column public.community_builds.management_token_hash is
  'HMAC-SHA-256 of the one-time management token returned to the publisher.';

create index if not exists community_builds_public_feed_idx
  on public.community_builds (created_at desc, id desc)
  where status = 'published';
create index if not exists community_builds_archetype_idx
  on public.community_builds (archetype_id, created_at desc)
  where status = 'published';

alter table public.community_builds enable row level security;

drop policy if exists "Community builds are publicly readable" on public.community_builds;
create policy "Community builds are publicly readable"
  on public.community_builds
  for select
  to anon, authenticated
  using (status = 'published');

-- RLS is row-level, so column grants are also required to keep the management
-- hash and moderation status out of direct Data API responses.
revoke all on table public.community_builds from anon, authenticated;
grant select (
  id, author_name, build_name, build_code, build_version,
  archetype_id, positions, level, created_at
) on table public.community_builds to anon, authenticated;
grant all on table public.community_builds to service_role;

create table if not exists public.community_rate_limit_events (
  id bigint generated by default as identity primary key,
  action text not null,
  actor_hash text not null,
  build_id uuid references public.community_builds(id) on delete set null,
  created_at timestamptz not null default clock_timestamp(),

  constraint community_rate_limit_action check (action in ('challenge', 'publish')),
  constraint community_rate_limit_actor_hash
    check (actor_hash ~ '^[0-9a-f]{64}$')
);

comment on table public.community_rate_limit_events is
  'Rate-limit attempts. actor_hash is a keyed HMAC, never a raw IP address.';

create index if not exists community_rate_limit_lookup_idx
  on public.community_rate_limit_events (action, actor_hash, created_at desc);
create index if not exists community_rate_limit_created_idx
  on public.community_rate_limit_events (created_at);

alter table public.community_rate_limit_events enable row level security;
revoke all on table public.community_rate_limit_events from public, anon, authenticated;
grant all on table public.community_rate_limit_events to service_role;

-- Atomically consumes one quota slot. The advisory transaction lock prevents
-- concurrent requests for the same actor from racing past the limit.
create or replace function public.community_consume_rate_limit(
  p_action text,
  p_actor_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns table (
  allowed boolean,
  event_id bigint,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_count integer;
  v_oldest timestamptz;
  v_event_id bigint;
  v_retry integer;
begin
  if p_action not in ('challenge', 'publish')
     or p_actor_hash !~ '^[0-9a-f]{64}$'
     or p_limit not between 1 and 100
     or p_window_seconds not between 60 and 86400 then
    raise exception 'invalid rate limit parameters' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_action || ':' || p_actor_hash, 0)
  );

  -- The indexed global cleanup also removes events belonging to actors who
  -- never return, keeping the audit table bounded.
  delete from public.community_rate_limit_events
  where created_at < v_now - interval '7 days';

  select count(*)::integer, min(created_at)
    into v_count, v_oldest
  from public.community_rate_limit_events
  where action = p_action
    and actor_hash = p_actor_hash
    and created_at > v_now - make_interval(secs => p_window_seconds);

  if v_count >= p_limit then
    v_retry := greatest(
      1,
      ceil(extract(epoch from (
        v_oldest + make_interval(secs => p_window_seconds) - v_now
      )))::integer
    );
    return query select false, null::bigint, v_retry;
    return;
  end if;

  insert into public.community_rate_limit_events (action, actor_hash)
  values (p_action, p_actor_hash)
  returning id into v_event_id;

  return query select true, v_event_id, 0;
end;
$$;

revoke all on function public.community_consume_rate_limit(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.community_consume_rate_limit(text, text, integer, integer)
  to service_role;

-- The Edge Function computes the HMAC and this function performs the comparison
-- and deletion in one statement. A false result does not reveal whether the id
-- or token was wrong.
create or replace function public.community_delete_build(
  p_build_id uuid,
  p_management_token_hash text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_deleted integer;
begin
  if p_management_token_hash !~ '^[0-9a-f]{64}$' then
    return false;
  end if;

  delete from public.community_builds
  where id = p_build_id
    and management_token_hash = p_management_token_hash;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$$;

revoke all on function public.community_delete_build(uuid, text)
  from public, anon, authenticated;
grant execute on function public.community_delete_build(uuid, text)
  to service_role;
